apiVersion: v1
metadata:
  name: bifrost-conf
kind: ConfigMap
data:
  bifrost-conf.cfg: |-
    port = 8000
    using_proxy = false
    access-control-allow-origin-header = "*"

    [bitcoin]
    master_public_key = "xpub661MyMwAqRbcEv5yXKguhEQbUaGT5jn8ketXeqy6JEzyCavk4zUGMDtJ2nmRwWVVXt3vStuHg8E6HwdHtQDsemj5G2QFF7MAhmssPrWuZ8E"
    rpc_server = "bitcoin-core:18332"
    rpc_user = "foo"
    rpc_pass = "bar"
    testnet = true
    minimum_value_btc = "0.0001"

    [ethereum]
    master_public_key = "xpub661MyMwAqRbcEv5yXKguhEQbUaGT5jn8ketXeqy6JEzyCavk4zUGMDtJ2nmRwWVVXt3vStuHg8E6HwdHtQDsemj5G2QFF7MAhmssPrWuZ8E"
    rpc_server = "ethereum-geth:8545"
    network_id = "3"
    minimum_value_eth = "0.00001"

    [stellar]
    issuer_public_key = "GCZAKXMQZKYJBQK7U2LFIF77PKGDCZRU3IOPV2VON5CHWJSWDH2B5A42"
    signer_secret_key = "${SIGNER_SECRET_KEY}"
    token_asset_code = "ALX1"
    needs_authorize = false
    horizon = "https://horizon-testnet.stellar.org"
    network_passphrase = "Test SDF Network ; September 2015"

    [database]
    type="postgres"
    dsn="postgres://${DB_USER}:${DB_PASSWORD}@postgres/myDB?sslmode=disable"
    migrationFilePath="/migrations"
