apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoin-core-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bitcoin-core
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bitcoin-core
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bitcoin-core
    spec:
      containers:
      - name: bitcoin-core
        args:
          - '-printtoconsole'
          - '-rpcallowip=0.0.0.0/0'
          - '-rpcuser=foo'
          - '-rpcpassword=bar'
          - '-testnet'
        image: ruimarinho/bitcoin-core:0.15.1-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: rpc-testnet
          containerPort: 18332
          protocol: TCP
        volumeMounts:
          - mountPath: /home/bitcoin/.bitcoin/
            name: bitcoin-storage-volume
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 64Mi
            cpu: 150m
      volumes:
      - name: bitcoin-storage-volume
        persistentVolumeClaim:
          claimName: bitcoin-core-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: bitcoin-core
  labels:
    app: bitcoin-core
spec:
  type: NodePort
  ports:
  - port: 18332
  selector:
    app: bitcoin-core
