apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ethereum-geth
  labels:
    app: ethereum-geth
spec:
  serviceName: ethereum-geth
  replicas: 1
  template:
    metadata:
      labels:
        app: ethereum-geth
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
      - name: ethereum-geth
        args:
          - '--testnet'
          - '--fast'
          - '--cache=128'
          - '--rpc'
          - '--rpcaddr=0.0.0.0'
          - '--datadir="/root/.ethereum"'
        image: ethereum/client-go:v1.7.3
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /root/
          name: geth-storage-volume
        ports:
        - name: rpc
          containerPort: 8545
          protocol: TCP
        - name: network
          containerPort: 30303
          protocol: TCP
        resources:
          limits:
            memory: 2Gi
            cpu: 450m
          requests:
            memory: 2Gi
            cpu: 300m
  volumeClaimTemplates:
    - metadata:
        name: geth-storage-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ethereum-geth
  labels:
    app: ethereum-geth
spec:
  type: ClusterIP
  ports:
  - port: 8545
  selector:
    app: ethereum-geth
